spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true